apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-medicos
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-medicos
  template:
    metadata:
      labels:
        app: ms-medicos
    spec:
      serviceAccountName: irsasecrets
      containers:
        - name: ms-medicos
          image: 851725345801.dkr.ecr.us-east-1.amazonaws.com/ms-medicos:{{VERSION}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.25"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: MONGODB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: documentdb-secret-medicos
                  key: urlMedicos
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "aws-secrets-ms-medicos"  # Nome do seu SecretProviderClass
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-medicos
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-medicos
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
