apiVersion: v1
kind: Service
metadata:
  name: ms-medicos
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  selector:
    app: ms-medicos
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3333
    nodePort: 30002
