apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-ms-medicos
spec:
  provider: aws
  secretObjects:
  - data:
    - key: urlMedicos
      objectName: urlMedicos
    secretName: documentdb-secret-medicos
    type: Opaque
  parameters:
    objects: |
        - objectName: "arn:aws:secretsmanager:us-east-1:851725345801:secret:documentdbcredentials-gxwTek"
          objectType: "secretsmanager"
          jmesPath:
            - path: "urlMedicos"
              objectAlias: "urlMedicos"
